version: '3'

services:
  app:
    build: .
    ports:
      - '4001:3000'
    volumes:
      - .:/home/node/app
    container_name: stock-API
    restart: always
    depends_on:
      - db
      - redis

  db:
    env_file:
      - ./envs/.env
    platform: linux/x86_64
    image: postgres:14
    container_name: database-stock
    restart: always
    ports:
      - 5435:5432

    volumes:
      - .postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stockDb
  redis:
    env_file:
      - ./envs/.env
    image: redis
    container_name: app-stock-redis
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - 6380:6379
    environment:
      - REDIS_PASSWORD=redisDev123

  rabbitmq:
    platform: linux/arm/v7
    image: rabbitmq:3.9.11-management
    container_name: rabbitmq-stock
    ports:
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  redis-data:
