export enum DepartamentsEnum {
  'ADMINISTRACAO' = 'ADMINISTRACAO',
  'FINANCEIRO' = 'FINANCEIRO',
  'COMERCIAL' = 'COMERCIAL',
  'TECNOLOGIA' = 'TECNOLOGIA',
  'CONTABILIDADE' = 'CONTABILIDADE',
  'MARKETING' = 'MARKETING',
  'LOGISTICA' = 'LOGISTICA',
  'RH' = 'RH'
}
